language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo apt-get install -qq libgtest-dev
  - mkdir build-gtest
  - cd build-gtest
  - cmake /usr/src/gtest
  - cmake --build .
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
    
script:
  - cmake .
  - cmake --build .
  - ctest -V
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T otus_cpp_lesson_06-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uchernikoff:$BINTRAY_API_KEY "https://api.bintray.com/content/chernikoff/otus/lesson_06/$TRAVIS_BUILD_NUMBER/otus_cpp_lesson_06-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1;"
